### PR TITLE
conan: Remove qwt include prefix

### PR DESCRIPTION
**Pull request by EstebanDugueperoux2**
- Remove qwt include prefix to be compatible with current consumption of 6.2.0 release through conan center.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
That choice was made to allow distribution packagers to co-install qwt-qt5 and qwt-qt6.
It is very common for many packages to install their headers in a subdirectory of `include` to not conflict with any other package.

**Comment by EstebanDugueperoux2** [comment]
Ok thanks, I understand that the error is in conan recipe.

**Comment by MehdiChinoune** [comment]
> Ok thanks, I understand that the error is in conan recipe.

No, they all patch qmake files to change the installation destination directory for header files.

**Comment by MehdiChinoune** [comment]
@EstebanDugueperoux2 I have added an option to set where to install header files in https://github.com/MehdiChinoune/qwt/commit/517a991e05289d43c3806c7768a714d4fa9fbf83 (`QWT_INSTALL_INCLUDE_DIR`)

**Pull request closed without merging**
