### PR TITLE
Replace default warning flag 

### PR DESCRIPTION
**Pull request by Jihadist**
Replace default warning flag /w3 by /w4 instead of appending to existing flags
Due to: ```cl : Command line warning D9025: overriding '/W3' with '/W4'```
P.s. Problem desribed here in mailing list https://cmake.org/pipermail/cmake/2018-December/068716.html

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
I don't see these messages with MSVC

**Comment by Jihadist** [comment]
I don't see these messages if i compile qwt as a single project. But if I add qwt to another project as sudbirectory I'll see this.

**Comment by Jihadist** [comment]
What's wrong with macos?

**Comment by MehdiChinoune** [comment]
> What's wrong with macos?

Probably a conflict between static and dynamic frameworks!

**Comment by MehdiChinoune** [comment]
@Jihadist Could you test the changes and see if they silent those warnings.

**Comment by Jihadist** [comment]
Flags -fno-math-errno -funsafe-math-optimizations change behaviour so if we use it in qwt as a top project it also should be used in qwt as subproject

**Comment by MehdiChinoune** [comment]
This repo is for porting Qwt from qmake to cmake to be built as a standalone project.
I am going to close this PR.

**Pull request closed without merging**
